package com.tanim.androidbasetemplate.utils

object DateFormat {
    const val DATE_FORMAT_E_dd_MMM_yyyy = "E, dd MMM yyyy"
    const val DATE_FORMAT_dd_MMM_yy_EEEE = "dd MMM yy, EEEE"
    const val DATE_FORMAT_dd_MMM_yy = "dd MMM yy"
    const val DATE_FORMAT_ddMMyyyy = "ddMMyyyy"
    const val DATE_FORMAT_yyyyMMdd = "yyyyMMdd"
    const val DATE_FORMAT_yyMMdd = "yyMMdd"
    const val DATE_FORMAT_yyyy__MM__dd = "yyyy/MM/dd"
    const val DATE_FORMAT_dd__MM__yyyy = "dd/MM/yyyy"
    const val DATE_FORMAT_E_hh_mm_dd_MMM_yyyy = "E, hh:mm a dd MMM yyyy"
    const val DATE_FORMAT_hh_a_mm_dd_MMM_yy = "hh:mm a dd MMM yy"
    const val DATE_FORMAT_hh_mm_dd_MMM_yy = "hh:mm, dd MMM yy"
    const val DATE_FORMAT_dd_MMM_yyyy = "dd MMM yyyy"
    const val DATE_FORMAT_dd_MM_yyyy = "dd-MM-yyyy"
    const val DATE_FORMAT_yyyy_MM_dd_hh_mm_ss = "yyyy-MM-dd hh:mm:ss"
    const val DATE_TIME_FORMAT = "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
    const val DATE_FORMAT_yyyy_MM_dd = "yyyy-MM-dd"
    const val DATE_FORMAT_MMM_dd_EEEE = "MMM dd, EEEE"
    const val DATE_FORMAT_MMMM_dd_EEEE = "MMMM dd, EEEE"
    const val DATE_FORMAT_MMM_dd_yyyy = "MMM dd, yyyy"
    const val DATE_FORMAT_day_name_full = "EEEE"
    const val DATE_FORMAT_MMM_dd = "MMM dd"
    const val DATE_FORMAT_dd_MMM = "dd MMM"
    const val DATE_FORMAT_day_name_short = "E"
    const val DATE_FORMAT_TIME_DDMMYYYY = "HHmmDDMMYYYY"
    const val CLOCK_TIME_FORMAT = "hh:mm a"
    const val DATE_FORMAT_yyyy = "yyyy"
}